apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
type: Opaque
data:
  DB_USERNAME: bXlhcHBfdXNlcg==  # base64 encoded value of 'myapp_user'
  DB_PASSWORD: bXlhcHBfcGFzc3dvcmQ=  # base64 encoded value of 'myapp_password'